Stage0:
  # Save folder
  SAVE_FOLDER_NAME: /home/c95hcw/ASR_Data/Dataset/speech_ttt/

  # Input Folder Parameters
  INPUT_FILES:
    Data_process1:
      # file name
      DATA_FOLDER: /home/c95hcw/ASR_Data/Dataset/raw_data/20210322_speech_tw/
      INTPUT_CSV_PATH: 91BqH/91BqH.csv
      CSV_COLUMN_WAV: Wave_path
      CSV_COLUMN_LABEL: Labels

      # Parameters of audio file
      SAVE_NEW_WAVE: True  
      SAMPLERATE: 16000
      WAVE_TIME_THRESHOLD: 30

      # parameters of split csv data
      SPLIT_RATIO: 0.5 
      # Vocab # Random # Sequence 
      SPLIT_MODE: Sequence 
      SEED: 3

      # parameters of if expand data
      DATA_EXPAND_value: 0.2 

    Data_process2:
      # file name
      DATA_FOLDER: /home/c95hcw/ASR_Data/Dataset/raw_data/
      INTPUT_CSV_PATH: my_record_2.csv
      CSV_COLUMN_WAV: Wave_path
      CSV_COLUMN_LABEL: Labels

      # Parameters of audio file
      SAVE_NEW_WAVE: False  
      SAMPLERATE: 16000
      WAVE_TIME_THRESHOLD: 30

      # parameters of split csv data
      SPLIT_RATIO: 1.0
      # Vocab # Random # Sequence 
      SPLIT_MODE: Vocab 
      SEED: 3

      # parameters of if expand data
      DATA_EXPAND_value: 0.0 

Stage1:
  # Save folder
  SAVE_FOLDER_NAME: /home/c95hcw/ASR_Data/Dataset/speech_ttt/

  # Input mode
  PROCESS_MODES: 
    - MASR
    - Quartznet
    - Espnet
    # - ASR_Inference_mode 